const types = {
  CREATE_SMS_SUCCESS: 'CREATE_SMS_SUCCESS',
  CREATE_SMS_ERROR: 'CREATE_SMS_ERROR',
  GET_SMS_PROFILE_SUCCESS: 'GET_SMS_PROFILE_SUCCESS',
  GET_SMS_PROFILE_ERROR: 'GET_SMS_PROFILE_ERROR',
  DEL_SMS_PROFILE_SUCCESS: 'DEL_SMS_PROFILE_SUCCESS',
  DEL_SMS_PROFILE_ERROR: 'DEL_SMS_PROFILE_ERROR',
  UPDATE_SMS_PROFILE_SUCCESS: 'UPDATE_SMS_PROFILE_SUCCESS',
  UPDATE_SMS_PROFILE_ERROR: 'UPDATE_SMS_PROFILE_ERROR',
};

export default types;
