const types = {
  CREATE_VERIFY_SUCCESS: 'CREATE_VERIFY_SUCCESS',
  CREATE_VERIFY_ERROR: 'CREATE_VERIFY_ERROR',
  GET_VERIFY_PROFILE_SUCCESS: 'GET_VERIFY_PROFILE_SUCCESS',
  GET_VERIFY_PROFILE_ERROR: 'GET_VERIFY_PROFILE_ERROR',
  DEL_VERIFY_PROFILE_SUCCESS: 'DEL_VERIFY_PROFILE_SUCCESS',
  DEL_VERIFY_PROFILE_ERROR: 'DEL_VERIFY_PROFILE_ERROR',
  UPDATE_VERIFY_PROFILE_SUCCESS: 'UPDATE_VERIFY_PROFILE_SUCCESS',
  UPDATE_VERIFY_PROFILE_ERROR: 'UPDATE_VERIFY_PROFILE_ERROR',
};

export default types;
