const PaymentTypes = {
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAIL: 'PAYMENT_FAIL',
  USER_CREDIT_SUCCESS: 'USER_CREDIT_SUCCESS',
  USER_CREDIT_FAIL: 'USER_CREDIT_FAIL'
};

export default PaymentTypes;
